const getAddExpenseStyles = (isDark, isMobile = false) => ({
  page: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: isDark
      ? "linear-gradient(135deg, #0f0c29 0%, #302b63 100%)"
      : "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    transition: "background 0.3s",
    padding: isMobile ? "0 12px 24px" : "0 16px 32px",
  },
  topHeader: {
    width: "100%",
    maxWidth: "900px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: isMobile ? "12px 0" : "16px 0",
    boxSizing: "border-box",
  },
  card: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "16px",
    padding: isMobile ? "28px 20px" : "48px 40px",
    width: "100%",
    maxWidth: "420px",
    boxShadow: isDark
      ? "0 20px 60px rgba(0,0,0,0.5)"
      : "0 20px 60px rgba(0,0,0,0.2)",
    transition: "background 0.3s",
  },
  title: {
    textAlign: "center",
    fontSize: "24px",
    fontWeight: "700",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
    marginBottom: "28px",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: "600",
    color: isDark ? "#b0b0cc" : "#555",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "15px",
    outline: "none",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    background: isDark ? "#16213e" : "#fafafa",
    transition: "background 0.3s, border-color 0.3s",
    marginBottom: "20px",
  },
  submitBtn: {
    width: "100%",
    padding: "13px",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    marginTop: "8px",
  },
  backBtn: {
    padding: "9px 18px",
    background: "rgba(255,255,255,0.15)",
    color: "#fff",
    border: "1.5px solid rgba(255,255,255,0.4)",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    backdropFilter: "blur(4px)",
  },
  checkRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "14px",
    fontWeight: "600",
    color: isDark ? "#b0b0cc" : "#555",
    marginBottom: "20px",
    cursor: "pointer",
    userSelect: "none",
  },
  errorBox: {
    background: isDark ? "#3d1a1a" : "#fff0f0",
    color: isDark ? "#fc8181" : "#e53e3e",
    padding: "10px 14px",
    borderRadius: "8px",
    fontSize: "13px",
    marginBottom: "16px",
  },
  successBox: {
    background: isDark ? "#1a3d2e" : "#f0fff4",
    color: isDark ? "#68d391" : "#276749",
    padding: "10px 14px",
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: "600",
    marginBottom: "16px",
    textAlign: "center",
  },
});

export default getAddExpenseStyles;
