const getAuthStyles = (isDark) => ({
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: isDark
      ? "linear-gradient(135deg, #0f0c29 0%, #302b63 100%)"
      : "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    transition: "background 0.3s",
  },
  card: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "16px",
    padding: "48px 40px",
    width: "100%",
    maxWidth: "400px",
    boxShadow: isDark
      ? "0 20px 60px rgba(0,0,0,0.5)"
      : "0 20px 60px rgba(0,0,0,0.2)",
    transition: "background 0.3s, box-shadow 0.3s",
  },
  logo: {
    textAlign: "center",
    marginBottom: "8px",
  },
  logoIcon: {
    fontSize: "40px",
  },
  title: {
    textAlign: "center",
    fontSize: "26px",
    fontWeight: "700",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
    margin: "0 0 4px",
    transition: "color 0.3s",
  },
  subtitle: {
    textAlign: "center",
    fontSize: "14px",
    color: isDark ? "#9090b8" : "#888",
    marginBottom: "32px",
    transition: "color 0.3s",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: "600",
    color: isDark ? "#b0b0cc" : "#555",
    marginBottom: "6px",
    transition: "color 0.3s",
  },
  inputWrapper: {
    marginBottom: "20px",
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "15px",
    outline: "none",
    transition: "border-color 0.2s, background 0.3s, color 0.3s",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    background: isDark ? "#16213e" : "#fafafa",
  },
  select: {
    width: "100%",
    padding: "12px 36px 12px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "15px",
    outline: "none",
    transition: "border-color 0.2s, background-color 0.3s, color 0.3s",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    backgroundColor: isDark ? "#16213e" : "#fafafa",
    appearance: "none",
    WebkitAppearance: "none",
    backgroundImage: isDark
      ? "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath d='M1 1l5 5 5-5' stroke='%239090b8' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E\")"
      : "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath d='M1 1l5 5 5-5' stroke='%23888' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 14px center",
    backgroundSize: "12px 8px",
    cursor: "pointer",
  },
  primaryBtn: {
    width: "100%",
    padding: "13px",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    marginTop: "8px",
    transition: "opacity 0.2s",
  },
  outlineBtn: {
    width: "100%",
    padding: "12px",
    background: "transparent",
    color: isDark ? "#9090ee" : "#667eea",
    border: `1.5px solid ${isDark ? "#9090ee" : "#667eea"}`,
    borderRadius: "8px",
    fontSize: "15px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background 0.2s, color 0.2s, border-color 0.3s",
  },
  phoneRow: {
    display: "flex",
    gap: "8px",
    alignItems: "stretch",
  },
  countrySelect: {
    padding: "12px 28px 12px 10px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s, background-color 0.3s, color 0.3s",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    backgroundColor: isDark ? "#16213e" : "#fafafa",
    appearance: "none",
    WebkitAppearance: "none",
    backgroundImage: isDark
      ? "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6' viewBox='0 0 10 6'%3E%3Cpath d='M1 1l4 4 4-4' stroke='%239090b8' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E\")"
      : "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6' viewBox='0 0 10 6'%3E%3Cpath d='M1 1l4 4 4-4' stroke='%23888' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 8px center",
    backgroundSize: "10px 6px",
    cursor: "pointer",
    flexShrink: 0,
    width: "110px",
  },
  phoneInput: {
    flex: 1,
    padding: "12px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "15px",
    outline: "none",
    transition: "border-color 0.2s, background 0.3s, color 0.3s",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    background: isDark ? "#16213e" : "#fafafa",
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    margin: "20px 0",
    color: isDark ? "#5a5a7a" : "#bbb",
    fontSize: "13px",
    transition: "color 0.3s",
  },
  dividerLine: {
    flex: 1,
    height: "1px",
    background: isDark ? "#3a3a5c" : "#e0e0e0",
    transition: "background 0.3s",
  },
  error: {
    background: isDark ? "#3d1a1a" : "#fff0f0",
    color: isDark ? "#fc8181" : "#e53e3e",
    padding: "10px 14px",
    borderRadius: "8px",
    fontSize: "14px",
    marginBottom: "16px",
    border: `1px solid ${isDark ? "#822" : "#fecaca"}`,
    transition: "background 0.3s, color 0.3s",
  },
  success: {
    background: isDark ? "#1a3d2e" : "#f0fff4",
    color: isDark ? "#68d391" : "#276749",
    padding: "10px 14px",
    borderRadius: "8px",
    fontSize: "14px",
    marginBottom: "16px",
    border: `1px solid ${isDark ? "#276749" : "#9ae6b4"}`,
    transition: "background 0.3s, color 0.3s",
  },
});

export default getAuthStyles;
