const getDashboardStyles = (isDark) => ({
  page: {
    minHeight: "100vh",
    background: isDark ? "#0f0c29" : "#f0f2f8",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    padding: "32px 24px",
    transition: "background 0.3s, color 0.3s",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "28px",
    flexWrap: "wrap",
    gap: "12px",
    paddingRight: "100px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    margin: 0,
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  addBtn: {
    padding: "10px 20px",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    borderRadius: "8px",
    textDecoration: "none",
    fontWeight: "600",
    fontSize: "14px",
    whiteSpace: "nowrap",
  },
  logoutBtn: {
    padding: "10px 16px",
    background: "transparent",
    color: isDark ? "#fc8181" : "#e53e3e",
    border: `1.5px solid ${isDark ? "#fc8181" : "#e53e3e"}`,
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
  },
  summaryRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: "16px",
    marginBottom: "24px",
  },
  summaryCard: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: "20px 24px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    transition: "background 0.3s",
  },
  summaryLabel: {
    fontSize: "12px",
    fontWeight: "600",
    color: isDark ? "#9090b8" : "#888",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "6px",
  },
  summaryValue: {
    fontSize: "26px",
    fontWeight: "700",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  summaryAccent: {
    fontSize: "26px",
    fontWeight: "700",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    alignItems: "start",
  },
  card: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    transition: "background 0.3s",
  },
  cardTitle: {
    fontSize: "16px",
    fontWeight: "700",
    marginBottom: "16px",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    background: isDark ? "#16213e" : "#f7f8fc",
    color: isDark ? "#9090b8" : "#888",
    fontWeight: "600",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.4px",
    borderRadius: "6px",
  },
  td: {
    padding: "12px 12px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    color: isDark ? "#c8c8e8" : "#333",
    verticalAlign: "middle",
  },
  tdAmount: {
    padding: "12px 12px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    color: isDark ? "#c8c8e8" : "#333",
    verticalAlign: "middle",
    textAlign: "right",
    fontWeight: "600",
  },
  tdDate: {
    padding: "12px 12px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    color: isDark ? "#9090b8" : "#999",
    verticalAlign: "middle",
  },
  thRight: {
    textAlign: "right",
    padding: "10px 12px",
    background: isDark ? "#16213e" : "#f7f8fc",
    color: isDark ? "#9090b8" : "#888",
    fontWeight: "600",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.4px",
    borderRadius: "6px",
  },
  badge: (color) => ({
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
    background: color + "22",
    color: color,
  }),
  emptyText: {
    textAlign: "center",
    color: isDark ? "#5a5a7a" : "#bbb",
    padding: "32px 0",
    fontSize: "14px",
  },
  pieWrap: {
    maxWidth: "320px",
    margin: "0 auto",
  },
  legend: {
    marginTop: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "13px",
    color: isDark ? "#c8c8e8" : "#444",
  },
  legendLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  legendDot: (color) => ({
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    background: color,
    flexShrink: 0,
  }),
  legendValue: {
    fontWeight: "600",
  },
  latestEntry: {
    fontSize: "16px",
    paddingTop: "4px",
    fontWeight: "700",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
});

export default getDashboardStyles;
