const getDashboardStyles = (isDark, isMobile = false) => ({
  page: {
    minHeight: "100vh",
    background: isDark ? "#0f0c29" : "#f0f2f8",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    padding: isMobile ? "16px 12px" : "32px 24px",
    transition: "background 0.3s, color 0.3s",
  },
  header: {
    display: "flex",
    alignItems: isMobile ? "flex-start" : "center",
    justifyContent: "space-between",
    marginBottom: "28px",
    flexWrap: "wrap",
    gap: "12px",
    paddingRight: "0",
  },
  title: {
    fontSize: isMobile ? "18px" : "24px",
    fontWeight: "700",
    margin: 0,
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  addBtn: {
    padding: isMobile ? "8px 12px" : "10px 20px",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    borderRadius: "8px",
    textDecoration: "none",
    fontWeight: "600",
    fontSize: isMobile ? "13px" : "14px",
    whiteSpace: "nowrap",
  },
  logoutBtn: {
    padding: "10px 16px",
    background: "transparent",
    color: isDark ? "#fc8181" : "#e53e3e",
    border: `1.5px solid ${isDark ? "#fc8181" : "#e53e3e"}`,
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
  },
  summaryRow: {
    display: "grid",
    gridTemplateColumns: isMobile
      ? "repeat(2, 1fr)"
      : "repeat(auto-fit, minmax(160px, 1fr))",
    gap: "12px",
    marginBottom: "24px",
  },
  summaryCard: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: isMobile ? "14px 16px" : "20px 24px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    transition: "background 0.3s",
  },
  summaryLabel: {
    fontSize: "12px",
    fontWeight: "600",
    color: isDark ? "#9090b8" : "#888",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "6px",
  },
  summaryValue: {
    fontSize: isMobile ? "20px" : "26px",
    fontWeight: "700",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  summaryAccent: {
    fontSize: isMobile ? "20px" : "26px",
    fontWeight: "700",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr",
    gap: "24px",
    alignItems: "start",
  },
  card: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: isMobile ? "16px" : "24px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    transition: "background 0.3s",
  },
  cardTitle: {
    fontSize: "16px",
    fontWeight: "700",
    marginBottom: "16px",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    background: isDark ? "#16213e" : "#f7f8fc",
    color: isDark ? "#9090b8" : "#888",
    fontWeight: "600",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.4px",
    borderRadius: "6px",
  },
  td: {
    padding: "12px 12px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    color: isDark ? "#c8c8e8" : "#333",
    verticalAlign: "middle",
  },
  tdAmount: {
    padding: "12px 12px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    color: isDark ? "#c8c8e8" : "#333",
    verticalAlign: "middle",
    textAlign: "right",
    fontWeight: "600",
  },
  tdDate: {
    padding: "12px 12px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    color: isDark ? "#9090b8" : "#999",
    verticalAlign: "middle",
  },
  tdTo: {
    padding: "12px 12px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    color: isDark ? "#b794f4" : "#6b46c1",
    verticalAlign: "middle",
    fontSize: "13px",
    fontWeight: "500",
  },
  thRight: {
    textAlign: "right",
    padding: "10px 12px",
    background: isDark ? "#16213e" : "#f7f8fc",
    color: isDark ? "#9090b8" : "#888",
    fontWeight: "600",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.4px",
    borderRadius: "6px",
  },
  badge: (color) => ({
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
    background: color + "22",
    color: color,
  }),
  emptyText: {
    textAlign: "center",
    color: isDark ? "#5a5a7a" : "#bbb",
    padding: "32px 0",
    fontSize: "14px",
  },
  pieWrap: {
    maxWidth: "320px",
    margin: "0 auto",
  },
  legend: {
    marginTop: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "13px",
    color: isDark ? "#c8c8e8" : "#444",
  },
  legendLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  legendDot: (color) => ({
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    background: color,
    flexShrink: 0,
  }),
  legendValue: {
    fontWeight: "600",
  },
  latestEntry: {
    fontSize: "16px",
    paddingTop: "4px",
    fontWeight: "700",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  splitsBanner: {
    background: isDark ? "#2a1f3d" : "#ede9fe",
    border: `1.5px solid ${isDark ? "#7c3aed" : "#c4b5fd"}`,
    borderRadius: "12px",
    padding: "16px 20px",
    marginBottom: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "12px",
  },
  splitsBannerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  splitsBannerIcon: {
    fontSize: "24px",
  },
  splitsBannerText: {
    fontWeight: "700",
    fontSize: "15px",
    color: isDark ? "#c4b5fd" : "#6d28d9",
  },
  splitsBannerSub: {
    fontSize: "13px",
    color: isDark ? "#a78bfa" : "#7c3aed",
    marginTop: "2px",
  },
  splitsViewBtn: {
    padding: "9px 18px",
    background: "linear-gradient(135deg, #7c3aed, #6d28d9)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
    textDecoration: "none",
    whiteSpace: "nowrap",
  },
  incomingCard: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    marginBottom: "24px",
    transition: "background 0.3s",
  },
  incomingItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 14px",
    borderRadius: "10px",
    background: isDark ? "#16213e" : "#f7f8fc",
    marginBottom: "10px",
    flexWrap: "wrap",
    gap: "8px",
  },
  incomingLeft: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
  },
  incomingDesc: {
    fontWeight: "700",
    fontSize: "14px",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  incomingMeta: {
    fontSize: "12px",
    color: isDark ? "#9090b8" : "#888",
  },
  incomingRight: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  incomingShare: {
    fontWeight: "700",
    fontSize: "15px",
    background: "linear-gradient(135deg, #7c3aed, #6d28d9)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  incomingBadge: {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: "700",
    background: isDark ? "#2a1f3d" : "#ede9fe",
    color: isDark ? "#c4b5fd" : "#6d28d9",
  },
  notifBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "18px",
    height: "18px",
    borderRadius: "50%",
    background: "#e53e3e",
    color: "#fff",
    fontSize: "11px",
    fontWeight: "700",
    marginLeft: "6px",
    verticalAlign: "middle",
  },
  // ── Filter bar
  filterBar: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  filterSelect: {
    padding: "9px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "13px",
    background: isDark ? "#1e2845" : "#fff",
    color: isDark ? "#e8e8f4" : "#333",
    outline: "none",
    cursor: "pointer",
    flexShrink: isMobile ? 0 : 1,
    width: isMobile ? "100%" : "auto",
  },
  filterSearch: {
    flex: 1,
    minWidth: isMobile ? "100%" : "160px",
    padding: "9px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "13px",
    background: isDark ? "#1e2845" : "#fff",
    color: isDark ? "#e8e8f4" : "#333",
    outline: "none",
  },
  exportBtn: {
    padding: "9px 16px",
    background: isDark ? "#2a2a5a" : "#ede9fe",
    color: isDark ? "#b794f4" : "#6b46c1",
    border: `1.5px solid ${isDark ? "#5a4a9a" : "#c4b5fd"}`,
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  filterBadge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "12px",
    fontSize: "11px",
    fontWeight: "700",
    background: isDark ? "#2a2a5a" : "#ede9fe",
    color: isDark ? "#b794f4" : "#6b46c1",
    marginLeft: "10px",
  },
  // ── Edit modal
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  modal: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "14px",
    padding: isMobile ? "20px 16px" : "28px 24px",
    width: "100%",
    maxWidth: isMobile ? "calc(100vw - 32px)" : "360px",
    boxShadow: isDark
      ? "0 16px 48px rgba(0,0,0,0.6)"
      : "0 16px 48px rgba(0,0,0,0.2)",
  },
  modalTitle: {
    fontWeight: "700",
    fontSize: "16px",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
    marginBottom: "16px",
  },
  modalInput: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "14px",
    background: isDark ? "#16213e" : "#fafafa",
    color: isDark ? "#e8e8f4" : "#333",
    outline: "none",
    marginBottom: "12px",
    boxSizing: "border-box",
  },
  modalCheckRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "13px",
    fontWeight: "600",
    color: isDark ? "#b0b0cc" : "#555",
    marginBottom: "4px",
    cursor: "pointer",
  },
  modalSaveBtn: {
    flex: 1,
    padding: "10px",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
  },
  modalCancelBtn: {
    flex: 1,
    padding: "10px",
    background: "transparent",
    color: isDark ? "#9090b8" : "#888",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#ddd"}`,
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
  },
  // ── Table action icons
  tdActions: {
    padding: "8px 8px",
    borderBottom: `1px solid ${isDark ? "#2a2a4a" : "#f0f0f0"}`,
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  },
  editIcon: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    padding: "2px 4px",
    borderRadius: "4px",
    opacity: 0.7,
  },
  deleteIcon: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    padding: "2px 4px",
    borderRadius: "4px",
    opacity: 0.7,
  },
  recurringBadge: {
    marginLeft: "6px",
    fontSize: "12px",
  },
  // ── Empty state
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "32px 0",
    gap: "4px",
  },
  emptyStateText: {
    color: isDark ? "#5a5a7a" : "#bbb",
    fontSize: "13px",
    fontWeight: "600",
    textAlign: "center",
  },
  // ── Budget
  budgetBarWrap: {
    marginTop: "4px",
    marginBottom: "8px",
    paddingLeft: "18px",
  },
  budgetBarTrack: {
    height: "6px",
    borderRadius: "3px",
    background: isDark ? "#2a2a4a" : "#e9e4ff",
    overflow: "hidden",
    marginBottom: "3px",
  },
  budgetBarFill: {
    height: "100%",
    borderRadius: "3px",
    transition: "width 0.4s ease",
  },
  budgetLabel: {
    fontSize: "11px",
    fontWeight: "600",
  },
  budgetDeleteBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    color: isDark ? "#fc8181" : "#e53e3e",
    lineHeight: 1,
    padding: "0 2px",
  },
  budgetToggleBtn: {
    width: "100%",
    padding: "9px",
    background: "transparent",
    color: isDark ? "#9090ee" : "#667eea",
    border: `1.5px dashed ${isDark ? "#9090ee" : "#667eea"}`,
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  budgetForm: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  budgetInput: {
    padding: "9px 12px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "13px",
    background: isDark ? "#16213e" : "#fafafa",
    color: isDark ? "#e8e8f4" : "#333",
    outline: "none",
  },
  budgetSaveBtn: {
    flex: 1,
    padding: "9px",
    background: "linear-gradient(135deg, #38a169, #276749)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "13px",
    cursor: "pointer",
  },
  budgetCancelBtn: {
    flex: 1,
    padding: "9px",
    background: "transparent",
    color: isDark ? "#9090b8" : "#888",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#ddd"}`,
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "13px",
    cursor: "pointer",
  },
  // ── Pagination
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginTop: "16px",
    flexWrap: "wrap",
  },
  pageNumbers: {
    display: "flex",
    gap: "4px",
    flexWrap: "wrap",
  },
  pageBtn: (disabled) => ({
    padding: "6px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    background: disabled
      ? isDark
        ? "#16213e"
        : "#f0f0f0"
      : isDark
        ? "#1e2845"
        : "#fff",
    color: disabled
      ? isDark
        ? "#4a4a6a"
        : "#ccc"
      : isDark
        ? "#9090ee"
        : "#667eea",
    fontSize: "13px",
    fontWeight: "600",
    cursor: disabled ? "default" : "pointer",
  }),
  pageNumBtn: (active) => ({
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: "none",
    background: active
      ? "linear-gradient(135deg, #667eea, #764ba2)"
      : isDark
        ? "#16213e"
        : "#f7f8fc",
    color: active ? "#fff" : isDark ? "#9090b8" : "#666",
    fontSize: "13px",
    fontWeight: "700",
    cursor: "pointer",
  }),
});

export default getDashboardStyles;
