const getProfileMenuStyles = (isDark, isMobile = false) => ({
  wrapper: {
    position: "relative",
    flexShrink: 0,
  },
  btn: {
    width: "38px",
    height: "38px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    border: "none",
    fontSize: "16px",
    fontWeight: "700",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dropdown: {
    position: "absolute",
    top: "48px",
    right: isMobile ? "0" : "auto",
    left: isMobile ? "auto" : "50%",
    transform: isMobile ? "none" : "translateX(-50%)",
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    boxShadow: isDark
      ? "0 8px 32px rgba(0,0,0,0.5)"
      : "0 8px 32px rgba(0,0,0,0.15)",
    padding: "16px",
    minWidth: "200px",
    zIndex: 1100,
    border: `1px solid ${isDark ? "#3a3a5c" : "#eee"}`,
  },
  avatar: {
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    fontSize: "20px",
    fontWeight: "700",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 12px",
  },
  name: {
    textAlign: "center",
    fontWeight: "700",
    fontSize: "15px",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
    marginBottom: "4px",
  },
  mobile: {
    textAlign: "center",
    fontSize: "13px",
    color: isDark ? "#9090b8" : "#888",
    marginBottom: "16px",
  },
  divider: {
    height: "1px",
    background: isDark ? "#3a3a5c" : "#eee",
    marginBottom: "12px",
  },
  logoutBtn: {
    width: "100%",
    padding: "9px",
    background: "transparent",
    color: isDark ? "#fc8181" : "#e53e3e",
    border: `1.5px solid ${isDark ? "#fc8181" : "#e53e3e"}`,
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: "14px",
    cursor: "pointer",
  },
});

export default getProfileMenuStyles;
