const getSplitBillsStyles = (isDark, isMobile = false) => ({
  page: {
    minHeight: "100vh",
    background: isDark ? "#0f0c29" : "#f0f2f8",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    padding: isMobile ? "16px 12px" : "32px 24px",
    transition: "background 0.3s, color 0.3s",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "28px",
    flexWrap: "wrap",
    gap: "12px",
    paddingRight: "0",
  },
  title: {
    fontSize: isMobile ? "18px" : "24px",
    fontWeight: "700",
    margin: 0,
  },
  backBtn: {
    padding: isMobile ? "8px 14px" : "10px 20px",
    background: "transparent",
    color: isDark ? "#9090ee" : "#667eea",
    border: `1.5px solid ${isDark ? "#9090ee" : "#667eea"}`,
    borderRadius: "8px",
    fontWeight: "600",
    fontSize: isMobile ? "13px" : "14px",
    cursor: "pointer",
    textDecoration: "none",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: isMobile ? "1fr" : "1fr 1.4fr",
    gap: "24px",
    alignItems: "start",
  },
  card: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: isMobile ? "16px" : "24px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    transition: "background 0.3s",
    marginBottom: "24px",
  },
  cardTitle: {
    fontSize: "16px",
    fontWeight: "700",
    marginBottom: "20px",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: "600",
    color: isDark ? "#b0b0cc" : "#555",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    padding: "11px 14px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    backgroundColor: isDark ? "#16213e" : "#fafafa",
    transition: "border-color 0.2s, background-color 0.3s, color 0.3s",
    marginBottom: "16px",
  },
  inputWrapper: {
    marginBottom: "4px",
  },
  memberRow: {
    display: "flex",
    gap: "8px",
    marginBottom: "10px",
    alignItems: "center",
    flexWrap: isMobile ? "wrap" : "nowrap",
  },
  memberInput: {
    flex: 1,
    padding: "10px 12px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "13px",
    outline: "none",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    backgroundColor: isDark ? "#16213e" : "#fafafa",
    transition: "border-color 0.2s, background-color 0.3s, color 0.3s",
  },
  memberCountrySelect: {
    padding: "10px 24px 10px 8px",
    borderRadius: "8px",
    border: `1.5px solid ${isDark ? "#3a3a5c" : "#e0e0e0"}`,
    fontSize: "12px",
    outline: "none",
    boxSizing: "border-box",
    color: isDark ? "#e8e8f4" : "#333",
    backgroundColor: isDark ? "#16213e" : "#fafafa",
    appearance: "none",
    WebkitAppearance: "none",
    backgroundImage: isDark
      ? "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6' viewBox='0 0 10 6'%3E%3Cpath d='M1 1l4 4 4-4' stroke='%239090b8' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E\")"
      : "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6' viewBox='0 0 10 6'%3E%3Cpath d='M1 1l4 4 4-4' stroke='%23888' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 6px center",
    backgroundSize: "10px 6px",
    cursor: "pointer",
    flexShrink: 0,
    width: "90px",
    transition: "border-color 0.2s, background-color 0.3s, color 0.3s",
  },
  removeBtn: {
    padding: "8px 12px",
    background: isDark ? "#3d1a1a" : "#fff0f0",
    color: isDark ? "#fc8181" : "#e53e3e",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "16px",
    flexShrink: 0,
  },
  addMemberBtn: {
    width: "100%",
    padding: "10px",
    background: "transparent",
    color: isDark ? "#9090ee" : "#667eea",
    border: `1.5px dashed ${isDark ? "#9090ee" : "#667eea"}`,
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    marginBottom: "20px",
  },
  submitBtn: {
    width: "100%",
    padding: "13px",
    background: isDark
      ? "linear-gradient(135deg, #5a6aaa, #6b4d8a)"
      : "linear-gradient(135deg, #8fa5f0, #a07dd4)",
    color: isDark ? "#e8e8f4" : "#fff",
    border: "none",
    borderRadius: "8px",
    fontSize: "15px",
    fontWeight: "600",
    cursor: "pointer",
  },
  memberCount: {
    fontSize: "12px",
    color: isDark ? "#9090b8" : "#888",
    marginBottom: "12px",
  },
  checkRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "13px",
    fontWeight: "600",
    color: isDark ? "#b0b0cc" : "#555",
    marginBottom: "14px",
    cursor: "pointer",
    userSelect: "none",
  },
  selfBadge: {
    display: "inline-block",
    padding: "2px 10px",
    borderRadius: "12px",
    fontSize: "11px",
    fontWeight: "700",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    color: "#fff",
    marginLeft: "4px",
  },
  splitCard: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    marginBottom: "16px",
    transition: "background 0.3s",
  },
  splitHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "12px",
    flexWrap: "wrap",
    gap: "4px",
  },
  splitDesc: {
    fontWeight: "700",
    fontSize: "15px",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  splitAmount: {
    fontWeight: "700",
    fontSize: "18px",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  splitDate: {
    fontSize: "12px",
    color: isDark ? "#9090b8" : "#888",
    marginBottom: "12px",
  },
  splitNote: {
    fontSize: "12px",
    color: isDark ? "#a0a0c0" : "#666",
    fontStyle: "italic",
    marginBottom: "4px",
    marginTop: "2px",
  },
  memberList: {
    listStyle: "none",
    padding: 0,
    margin: "0 0 12px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  memberItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    borderRadius: "8px",
    background: isDark ? "#16213e" : "#f7f8fc",
    fontSize: "13px",
  },
  memberInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  memberName: {
    fontWeight: "600",
    color: isDark ? "#e8e8f4" : "#1a1a2e",
  },
  memberMobile: {
    color: isDark ? "#9090b8" : "#888",
    fontSize: "12px",
  },
  memberRight: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  memberShare: {
    fontWeight: "700",
    color: isDark ? "#e8e8f4" : "#333",
  },
  settleBtn: (settled) => ({
    padding: "4px 10px",
    borderRadius: "20px",
    border: "none",
    fontSize: "11px",
    fontWeight: "700",
    cursor: "pointer",
    background: settled
      ? isDark
        ? "#1a3d2e"
        : "#f0fff4"
      : isDark
        ? "#3a3a5c"
        : "#f0f0f0",
    color: settled
      ? isDark
        ? "#68d391"
        : "#276749"
      : isDark
        ? "#9090b8"
        : "#666",
  }),
  deleteBtn: {
    width: "100%",
    padding: "8px",
    background: "transparent",
    color: isDark ? "#fc8181" : "#e53e3e",
    border: `1px solid ${isDark ? "#fc8181" : "#e53e3e"}`,
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  emptyText: {
    textAlign: "center",
    color: isDark ? "#5a5a7a" : "#bbb",
    padding: "40px 0",
    fontSize: "14px",
  },
  perHeadBadge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "12px",
    fontSize: "11px",
    fontWeight: "600",
    background: isDark ? "#2a2a5a" : "#ede9fe",
    color: isDark ? "#b794f4" : "#6b46c1",
    marginLeft: "8px",
  },
  incomingSection: {
    background: isDark ? "#1e2845" : "#fff",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: isDark
      ? "0 4px 20px rgba(0,0,0,0.4)"
      : "0 4px 20px rgba(0,0,0,0.07)",
    marginBottom: "20px",
    transition: "background 0.3s",
  },
  incomingItem: {
    display: "flex",
    alignItems: isMobile ? "flex-start" : "center",
    justifyContent: "space-between",
    padding: "12px 14px",
    borderRadius: "10px",
    background: isDark ? "#16213e" : "#f7f8fc",
    marginBottom: "10px",
    gap: "12px",
    flexDirection: isMobile ? "column" : "row",
  },
  incomingLeft: {
    flex: 1,
    minWidth: 0,
  },
  incomingRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "6px",
    flexShrink: 0,
  },
  incomingShare: {
    fontWeight: "700",
    fontSize: "15px",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  payBtn: (paid) => ({
    padding: "6px 16px",
    borderRadius: "20px",
    border: "none",
    fontSize: "12px",
    fontWeight: "700",
    cursor: paid ? "default" : "pointer",
    background: paid
      ? isDark
        ? "#1a3d2e"
        : "#f0fff4"
      : "linear-gradient(135deg, #38a169, #276749)",
    color: paid ? (isDark ? "#68d391" : "#276749") : "#fff",
    opacity: paid ? 0.85 : 1,
    transition: "opacity 0.2s",
  }),
});

export default getSplitBillsStyles;
